# How works: cherry-pick the original commit that implemented this file to the main branch
# the main branch must be set as default branch in your Github repository
# every time you run a build will be automatically copied the "build_scripts" folder from the main branch to the branch to be builded
# by using the GUI user configuration of action page (workflow_dispatch inputs)
# when the action finish build an artifact, it will be automatically uploaded to the "Summary" page of the action workflow executed
name: CI - Manual artifacts building
on: 
  workflow_dispatch:
    inputs:
      platformArch:
        type: choice
        description: 'Select platform and architecture'
        required: true
        options:
        - windows-x86_64
        - windows-x86
        - windows
        - android-arm64
        - android-arm
        - android
        - linux-x86_64
        - linux-arm64
        - linux-arm
        - linux
        - macos-x86_64
        - all
      customISABranch:
        description: 'Specify ISAdaptive branch to be builded'
        required: true
        default: ''
      customKodiRepository:
        description: 'Specify the xbmc repository to use'
        required: true
        default: 'https://github.com/xbmc/xbmc'
      customKodiBranch:
        description: 'Override the default xbmc repository branch to use'
        required: true
        default: '-'
env:
  ADDON_ID: inputstream.adaptive
  ADDON_REPO: https://github.com/${{ github.repository }}
  CUSTOM_KODI_REPO: ${{ github.event.inputs.customKodiRepository }}
  CUSTOM_KODI_BRANCH: ${{ github.event.inputs.customKodiBranch }}
jobs:
  build-windows-x86:
    if: github.event.inputs.platformArch == 'all' || github.event.inputs.platformArch == 'windows' || github.event.inputs.platformArch == 'windows-x86'
    name: Build Windows x86
    runs-on: windows-2019
    env:
      KODI_VERSION: omega
      PLATFORM: windows
      ARCH: x86
    steps:
    - name: Check out ${{ github.event.inputs.customISABranch }} from repository ${{ github.repository }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.customISABranch }}
    - name: Copy build_scripts file from default branch
      uses: Bhacaz/checkout-files@v2
      with:
       files: build_scripts
    - name: Run build-isa.sh bash
      id: run-bash
      run: bash -x build-isa.sh
      shell: bash
      working-directory: build_scripts
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-bash.outputs.zip-name }}
        path: ${{ github.workspace }}/kodi-git/zip_content
  build-windows-x86_64:
    if: github.event.inputs.platformArch == 'all' || github.event.inputs.platformArch == 'windows' || github.event.inputs.platformArch == 'windows-x86_64' || github.event.inputs.platformArch == 'default'
    name: Build Windows x86_64
    runs-on: windows-2019
    env:
      KODI_VERSION: omega
      PLATFORM: windows
      ARCH: x86_64
    steps:
    - name: Check out ${{ github.event.inputs.customISABranch }} from repository ${{ github.repository }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.customISABranch }}
    - name: Copy build_scripts file from default branch
      uses: Bhacaz/checkout-files@v2
      with:
       files: build_scripts
    - name: Run build-isa.sh bash
      id: run-bash
      run: bash -x build-isa.sh
      shell: bash
      working-directory: build_scripts
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-bash.outputs.zip-name }}
        path: ${{ github.workspace }}/kodi-git/zip_content
  build-android-arm64:
    if: github.event.inputs.platformArch == 'all' || github.event.inputs.platformArch == 'android' || github.event.inputs.platformArch == 'android-arm64' || github.event.inputs.platformArch == 'default'
    name: Build Android aarch64
    runs-on: ubuntu-24.04
    env:
      KODI_VERSION: omega
      PLATFORM: android
      ARCH: aarch64
    steps:
    - name: Check out ${{ github.event.inputs.customISABranch }} from repository ${{ github.repository }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.customISABranch }}
    - name: Copy build_scripts file from default branch
      uses: Bhacaz/checkout-files@v2
      with:
       files: build_scripts
    - name: Run build-isa.sh bash
      id: run-bash
      run: bash -x build-isa.sh
      shell: bash
      working-directory: build_scripts
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-bash.outputs.zip-name }}
        path: ${{ steps.run-bash.outputs.zip-path }}
  build-android-arm:
    if: github.event.inputs.platformArch == 'all' || github.event.inputs.platformArch == 'android' || github.event.inputs.platformArch == 'android-arm'
    name: Build Android armv7
    runs-on: ubuntu-24.04
    env:
      KODI_VERSION: omega
      PLATFORM: android
      ARCH: armv7
    steps:
    - name: Check out ${{ github.event.inputs.customISABranch }} from repository ${{ github.repository }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.customISABranch }}
    - name: Copy build_scripts file from default branch
      uses: Bhacaz/checkout-files@v2
      with:
       files: build_scripts
    - name: Run build-isa.sh bash
      id: run-bash
      run: bash -x build-isa.sh
      shell: bash
      working-directory: build_scripts
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-bash.outputs.zip-name }}
        path: ${{ steps.run-bash.outputs.zip-path }}
  build-linux-x86_64:
    if: github.event.inputs.platformArch == 'all' || github.event.inputs.platformArch == 'linux' || github.event.inputs.platformArch == 'linux-x86_64' || github.event.inputs.platformArch == 'default'
    name: Build Linux x86_64
    runs-on: ubuntu-latest
    env:
      KODI_VERSION: omega
      PLATFORM: linux
      ARCH: x86_64
    steps:
    - name: Check out ${{ github.event.inputs.customISABranch }} from repository ${{ github.repository }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.customISABranch }}
    - name: Copy build_scripts file from default branch
      uses: Bhacaz/checkout-files@v2
      with:
       files: build_scripts
    - name: Run build-isa.sh bash
      id: run-bash
      run: bash -x build-isa.sh
      shell: bash
      working-directory: build_scripts
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-bash.outputs.zip-name }}
        path: ${{ steps.run-bash.outputs.zip-path }}
  build-linux-arm:
    if: github.event.inputs.platformArch == 'all' || github.event.inputs.platformArch == 'linux' || github.event.inputs.platformArch == 'linux-arm'
    name: Build Linux armv7
    runs-on: ubuntu-latest
    env:
      KODI_VERSION: omega
      PLATFORM: linux
      ARCH: armv7
    steps:
    - name: Check out ${{ github.event.inputs.customISABranch }} from repository ${{ github.repository }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.customISABranch }}
    - name: Copy build_scripts file from default branch
      uses: Bhacaz/checkout-files@v2
      with:
       files: build_scripts
    - name: Run build-isa.sh bash
      id: run-bash
      run: bash -x build-isa.sh
      shell: bash
      working-directory: build_scripts
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-bash.outputs.zip-name }}
        path: ${{ steps.run-bash.outputs.zip-path }}
  build-linux-arm64:
    if: github.event.inputs.platformArch == 'all' || github.event.inputs.platformArch == 'linux' || github.event.inputs.platformArch == 'linux-arm64'
    name: Build Linux aarch64
    runs-on: ubuntu-latest
    env:
      KODI_VERSION: omega
      PLATFORM: linux
      ARCH: aarch64
    steps:
    - name: Check out ${{ github.event.inputs.customISABranch }} from repository ${{ github.repository }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.customISABranch }}
    - name: Copy build_scripts file from default branch
      uses: Bhacaz/checkout-files@v2
      with:
       files: build_scripts
    - name: Run build-isa.sh bash
      id: run-bash
      run: bash -x build-isa.sh
      shell: bash
      working-directory: build_scripts
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-bash.outputs.zip-name }}
        path: ${{ steps.run-bash.outputs.zip-path }}
  build-macos:
    if: github.event.inputs.platformArch == 'all' || github.event.inputs.platformArch == 'macos' || github.event.inputs.platformArch == 'macos-x86_64'
    name: Build MacOs x86_64
    runs-on: macos-11.0
    env:
      KODI_VERSION: omega
      PLATFORM: darwin
      ARCH: x86_64
    steps:
    - name: Check out ${{ github.event.inputs.customISABranch }} from repository ${{ github.repository }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.customISABranch }}
    - name: Copy build_scripts file from default branch
      uses: Bhacaz/checkout-files@v2
      with:
       files: build_scripts
    - name: Run build-isa.sh bash
      id: run-bash
      run: bash -x build-isa.sh
      shell: bash
      working-directory: build_scripts
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-bash.outputs.zip-name }}
        path: ${{ steps.run-bash.outputs.zip-path }}
